#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Mar 15 13:39:43 -03 2019
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim mult_8bit_tb_behav -key {Behavioral:sim_1:Functional:mult_8bit_tb} -tclbatch mult_8bit_tb.tcl -view /home/mateus/ufc/FPGA_Projets/FPGA_Projets/mult_8bit/mult_8bit_tb_behav.wcfg -log simulate.log
