# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/mateus/ufc/FPGA_Projets/FPGA_Projets/mult_8bit/mult_8bit.cache/wt [current_project]
set_property parent.project_path /home/mateus/ufc/FPGA_Projets/FPGA_Projets/mult_8bit/mult_8bit.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:ac701:part0:1.3 [current_project]
set_property ip_output_repo /home/mateus/ufc/FPGA_Projets/FPGA_Projets/mult_8bit/mult_8bit.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/mateus/ufc/FPGA_Projets/FPGA_Projets/add_16bit/add_16bit.srcs/sources_1/new/add_16bit.v
  /home/mateus/ufc/FPGA_Projets/FPGA_Projets/mux_16bit/mux_16bit.srcs/sources_1/new/mux_16bit.v
  /home/mateus/ufc/FPGA_Projets/FPGA_Projets/shift_16bit/shift_16bit.srcs/sources_1/new/shift_16bit.v
  /home/mateus/ufc/FPGA_Projets/FPGA_Projets/mult_8bit/mult_8bit.srcs/sources_1/new/mult_8bit.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top mult_8bit -part xc7a200tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mult_8bit.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mult_8bit_utilization_synth.rpt -pb mult_8bit_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
